// <auto-generated />
using Budget.Core.Model;
using Budget.Data.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Budget.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20171128195603_AddBudgetClassFKMigration_BudgetDbContext")]
    partial class AddBudgetClassFKMigration_BudgetDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Budget.Core.Model.BudgetClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("BaseTotal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("SortOrder");

                    b.Property<int>("Tenant_Id");

                    b.Property<int>("TransactionType");

                    b.HasKey("Id");

                    b.HasIndex("Tenant_Id");

                    b.ToTable("BudgetClasses","Budget");
                });

            modelBuilder.Entity("Budget.Core.Model.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants","Tenants");
                });

            modelBuilder.Entity("Budget.Core.Model.BudgetClass", b =>
                {
                    b.HasOne("Budget.Core.Model.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("Tenant_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
