//------------------------------------------------------------------------------
//  BudgetClass.cs
//
//  Implementation of: BudgetClass (Class) <<ef-entity>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 02-jun-2017 10:49:07
//  Original author: Miguel
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace Budget.Core.Model
{
    public class BudgetClass
    {
        public virtual decimal BaseTotal { get; set; }

        public int Id { get; set; }

        [Required]
        [MaxLength(100)]
        public virtual string Name { get; set; } // Key data ----------

        public virtual Byte[] RowVersion { get; set; }

        public virtual int SortOrder { get; set; }

        public virtual TransactionType TransactionType { get; set; } = TransactionType.Income;
    }
}
