//------------------------------------------------------------------------------
//  Tenant.cs
//
//  Implementation of: Tenant (Class) <<ef-entity>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 06-ago-2017 19:29:24
//  Original author: Miguel
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace Budget.Core.Model
{
    // 6-1. Add tenant model
    //----------------------

    public class Tenant
    {
        public Tenant()
        {
        }

        public int Id { get; set; }

        [Required]
        [MaxLength(250)] // Default string length
        public virtual string Name { get; set; } // Key data ----------

        public virtual Byte[] RowVersion { get; set; }
    }
}