//------------------------------------------------------------------------------
//  TenantRepository.cs
//
//  Implementation of: TenantRepository (Class) <<entity-repository>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 02-jun-2017 10:49:07
//  Original author: Miguel
//------------------------------------------------------------------------------

using Budget.Core.Model;
using Domion.Data.Base;
using Domion.Lib;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace Budget.Data.Services
{
    // 6-4. Add TenantRepository
    //--------------------------

    public class TenantRepository : BaseRepository<Tenant>, IEntityQuery<Tenant>
    {
        public static readonly string DuplicateByNameError = @"There's another Tenant with Name ""{0}"", can't duplicate! (Id={1})";

        /// <inheritdoc />
        public TenantRepository(BudgetDbContext dbContext)
            : base(dbContext)
        {
        }

        public new IQueryable<Tenant> Query(Expression<Func<Tenant, bool>> where = null)
        {
            return base.Query(where);
        }

        public new virtual async Task<int> SaveChangesAsync()
        {
            return await base.SaveChangesAsync();
        }

        public new virtual async Task<List<ValidationResult>> TryDeleteAsync(Tenant entity)
        {
            if (entity.RowVersion == null || entity.RowVersion.Length == 0) throw new InvalidOperationException($"Missing {nameof(entity.RowVersion)} on Delete");

            return await base.TryDeleteAsync(entity);
        }

        public new virtual async Task<List<ValidationResult>> TryInsertAsync(Tenant entity)
        {
            if (entity.RowVersion != null && entity.RowVersion.Length > 0) throw new InvalidOperationException($"Existing {nameof(entity.RowVersion)} on Insert");

            CommonSaveOperations(entity);

            return await base.TryInsertAsync(entity);
        }

        public new virtual async Task<List<ValidationResult>> TryUpdateAsync(Tenant entity)
        {
            if (entity.RowVersion == null || entity.RowVersion.Length == 0) throw new InvalidOperationException($"Missing {nameof(entity.RowVersion)} on Update");

            CommonSaveOperations(entity);

            return await base.TryUpdateAsync(entity);
        }

        public virtual async Task<List<ValidationResult>> TryUpsertAsync(Tenant entity)
        {
            return entity.Id == 0 ? await TryInsertAsync(entity) : await TryUpdateAsync(entity);
        }

        /// <summary>
        ///     Performs operations that have to be executed both on inserts and updates.
        /// </summary>
        internal virtual void CommonSaveOperations(Tenant entity)
        {
            TrimStrings(entity);
        }

        protected override async Task<List<ValidationResult>> ValidateDeleteAsync(Tenant entity)
        {
            return await base.ValidateDeleteAsync(entity);
        }

        /// <inheritdoc />
        protected override async Task<List<ValidationResult>> ValidateSaveAsync(Tenant entity)
        {
            Tenant duplicateByName = await this.FindDuplicateByNameAsync(entity);

            if (duplicateByName != null)
            {
                return Errors.ErrorList(DuplicateByNameError, new object[] { duplicateByName.Name, duplicateByName.Id }, new[] { "Name" });
            }

            return Errors.NoError;
        }

        private void TrimStrings(Tenant entity)
        {
            entity.Name = entity.Name?.Trim();
        }
    }
}
